### ISSUE TITLE
fast_sync fails to import fetched DB

### ISSUE THREAD

**Issue by nsipplswezey** [blockstack/blockstack-core#758]
While working through newly released developer docs in README.md, specifically following steps at https://github.com/blockstack/blockstack-core#setting-up-blockstack-core command `blockstack-core --debug fast_sync` fails. Log below.

Searched for where the public key referenced in `By default, it will pull a snapshot from http://fast-sync.blockstack.org/snapshot.bsk and use a built-in public key to verify its authenticity.` might exist, and whether that's consistent with my debug output.

Best I could find was https://github.com/blockstack/blockstack-core/blob/c02d964734f5cd8d008299dd8706ebb45ca443f4/blockstack/lib/config.py#L60-L62

Referenced in https://github.com/blockstack/blockstack-core/blob/c02d964734f5cd8d008299dd8706ebb45ca443f4/blockstack/lib/fast_sync.py#L512-L520

Which seems inconsistent with the public key in my log output, though unclear to me if that's actually the underlying issue, or if it's something else.

 ```
Macintosh-7:BlockStack nsipplswezey$ blockstack-core --debug fast_sync
[2018-02-22 20:55:22,790] [DEBUG] [spv:103] (14138.140735599272768) Using mainnet
[2018-02-22 20:55:22,955] [DEBUG] [blockstackd:2718] (14138.140735599272768) Working dir: /Users/nsipplswezey/.blockstack-server
[2018-02-22 20:55:22,955] [DEBUG] [config:1270] (14138.140735599272768) Load config from '/Users/nsipplswezey/.blockstack-server/blockstack-server.ini'
[2018-02-22 20:55:22,967] [DEBUG] [blockstackd:2735] (14138.140735599272768) config:
{
    "bitcoind": {
        "bitcoind_p2p_port": 8333, 
        "bitcoind_passwd": "blockstacksystem", 
        "bitcoind_port": 8332, 
        "bitcoind_regtest": false, 
        "bitcoind_server": "bitcoin.blockstack.com", 
        "bitcoind_spv_path": "/Users/nsipplswezey/.virtualchain-spv-headers.dat", 
        "bitcoind_timeout": 300.0, 
        "bitcoind_user": "blockstack"
    }, 
    "blockstack": {
        "announcers": "judecn.id,muneeb.id,shea256.id", 
        "atlas": true, 
        "atlas_blacklist": "", 
        "atlas_hostname": "Macintosh-7", 
        "atlas_seeds": "node.blockstack.org:6264", 
        "atlasdb_path": "/Users/nsipplswezey/.blockstack-server/atlas.db", 
        "backup_frequency": 144, 
        "backup_max_age": 1008, 
        "data_storage_drivers": "disk", 
        "data_storage_drivers_write": "disk", 
        "email": "nsipplswezey@gmail.com", 
        "profile_storage_drivers": "disk", 
        "profile_storage_drivers_write": "disk", 
        "redirect_data": false, 
        "rpc_port": 6264, 
        "serve_data": false, 
        "serve_profiles": false, 
        "serve_zonefiles": true, 
        "server_version": "0.17.0.16", 
        "zonefile_storage_drivers": "disk,dht", 
        "zonefile_storage_drivers_write": "disk", 
        "zonefiles": "/Users/nsipplswezey/.blockstack-server/zonefiles"
    }
}
Synchronizing from snapshot from http://fast-sync.blockstack.org/snapshot.bsk.  This may take up to 15 minutes.
[2018-02-22 20:55:22,978] [DEBUG] [fast_sync:433] (14138.140735599272768) Fetch http://fast-sync.blockstack.org/snapshot.bsk to /var/folders/j8/zg8_6vn11qx7cfftkgxsyrv80000gn/T/.blockstack-fast-sync-MtbwgO...
Verify 206537885 bytes
[2018-02-22 20:57:48,191] [DEBUG] [ecdsalib:341] (14138.140735599272768) Bad signature mBjGsbQ6EZOaN2qPlFJHxHgdxcQD1qtPfrjZkcQAK2gFwm086zP4BZzX52d20ZGNEJscKnkx476ri5CZ58jCBQ==; not from 02edbaa730f241960bcd1a50c718fac7f9d4874f460c1f6db0a3941094e7685ef9 on d9cda92f1f09dcb9702c8ceebff54d01d1724a2fa4e0a201cd5e940cc732b578?
Public key 02edbaa730f241960bcd1a50c718fac7f9d4874f460c1f6db0a3941094e7685ef9 does NOT match mBjGsbQ6EZOaN2qPlFJHxHgdxcQD1qtPfrjZkcQAK2gFwm086zP4BZzX52d20ZGNEJscKnkx476ri5CZ58jCBQ== (d9cda92f1f09dcb9702c8ceebff54d01d1724a2fa4e0a201cd5e940cc732b578)
Not enough signatures match (required 1, found 0)
fast_sync failed
```

**Comment by jackzampolin** [comment]
@nsipplswezey It looks like you are still on version `0.17.0.16`. We released `0.18.0` this week. The keys for the fast sync server were changed in this release so this is likely the issue you are experiencing. Please upgrade and try again.

**Comment by nsipplswezey** [comment]
Great! Makes sense! Thanks!

**Comment by jackzampolin** [comment]
We do have a couple of couple of issues for better error management, but we can always use specific ones. This would be a great one to add. I've also been working on instructions for setting up your own fast_sync server that would be instructive in this situation. Also I will mention that PRs are always welcome 😉. Try manually changing that `0.17.0.16` number to `0.18.0.0` and see if that fixes your issue. 

Tagging @jcnelson here for more in depth suggestions. I'll also go ahead an reopen this issue and rename it to fast_sync import fails `0.18`

**Comment by nsipplswezey** [comment]
Awesome thanks @jackzampolin

**Comment by nsipplswezey** [comment]
Re: 
>Try manually changing that 0.17.0.16 number to 0.18.0.0 and see if that fixes your issue.

 Issue persist after manually changing `server_version` to `0.18.0.0` in `blockstack-server.ini` 

```
Macintosh-7:blockstack-core nsipplswezey$ blockstack-core --debug fast_sync
Re-exec as /usr/local/bin/blockstack-core fast_sync
[2018-02-23 11:17:12,434] [DEBUG] [spv:103] (17930.140735599272768) Using mainnet
[2018-02-23 11:17:12,514] [DEBUG] [blockstackd:2449] (17930.140735599272768) Stripped argv: /usr/local/bin/blockstack-core fast_sync
[2018-02-23 11:17:12,515] [DEBUG] [blockstackd:2285] (17930.140735599272768) Working dir: /Users/nsipplswezey/.blockstack-server
[2018-02-23 11:17:12,515] [DEBUG] [config:1338] (17930.140735599272768) Load config from '/Users/nsipplswezey/.blockstack-server/blockstack-server.ini'
[2018-02-23 11:17:12,518] [DEBUG] [blockstackd:2301] (17930.140735599272768) config:
{
    "bitcoind": {
        "bitcoind_p2p_port": 8333, 
        "bitcoind_passwd": "blockstacksystem", 
        "bitcoind_port": 8332, 
        "bitcoind_regtest": false, 
        "bitcoind_server": "bitcoin.blockstack.com", 
        "bitcoind_spv_path": "/Users/nsipplswezey/.virtualchain-spv-headers.dat", 
        "bitcoind_timeout": 300.0, 
        "bitcoind_user": "blockstack"
    }, 
    "blockstack": {
        "announcers": "judecn.id,muneeb.id,shea256.id", 
        "atlas": true, 
        "atlas_blacklist": "", 
        "atlas_hostname": "Macintosh-7", 
        "atlas_port": 6264, 
        "atlas_seeds": "node.blockstack.org:6264", 
        "atlasdb_path": "/Users/nsipplswezey/.blockstack-server/atlas.db", 
        "backup_frequency": 144, 
        "backup_max_age": 1008, 
        "rpc_port": 6264, 
        "server_version": "0.18.0.0", 
        "subdomaindb_path": "/Users/nsipplswezey/.blockstack-server/subdomains.db", 
        "zonefiles": "/Users/nsipplswezey/.blockstack-server/zonefiles"
    }
}
Synchronizing from snapshot from http://fast-sync.blockstack.org/snapshot.bsk.  This may take up to 15 minutes.
[2018-02-23 11:17:12,528] [DEBUG] [fast_sync:423] (17930.140735599272768) Fetch http://fast-sync.blockstack.org/snapshot.bsk to /var/folders/j8/zg8_6vn11qx7cfftkgxsyrv80000gn/T/.blockstack-fast-sync-Kmzus3...
Verify 206537885 bytes
[2018-02-23 11:22:04,403] [WARNING] [namedb:153] (17930.140735599272768) !!! Getting raw read/write DB instance !!!
[2018-02-23 11:22:04,404] [DEBUG] [namedb:91] (17930.140735599272768) Connect to database '/Users/nsipplswezey/.blockstack-server/blockstack-server.db'
[2018-02-23 11:22:04,421] [ERROR] [indexer:388] (17930.140735599272768) file is not a database
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 373, in db_query_execute
    ret = cur.execute(query, values)
DatabaseError: file is not a database
[2018-02-23 11:22:04,435] [ERROR] [indexer:389] (17930.140735599272768) FATAL: failed to execute query (SELECT MAX(block_id) FROM snapshots;, ())
[2018-02-23 11:22:04,444] [ERROR] [indexer:390] (17930.140735599272768)   File "/usr/local/bin/blockstack-core", line 42, in <module>
    run_blockstackd()

  File "/usr/local/lib/python2.7/site-packages/blockstack/blockstackd.py", line 2836, in run_blockstackd
    rc = fast_sync_import(working_dir, url, public_keys=public_keys, num_required=num_required, verbose=True)

  File "/usr/local/lib/python2.7/site-packages/blockstack/lib/fast_sync.py", line 600, in fast_sync_import
    rc = blockstack_backup_restore(working_dir, None)

  File "/usr/local/lib/python2.7/site-packages/blockstack/lib/fast_sync.py", line 620, in blockstack_backup_restore
    db = BlockstackDB.get_readwrite_instance(working_dir, restore=True, restore_block_height=block_number)

  File "/usr/local/lib/python2.7/site-packages/blockstack/lib/nameset/namedb.py", line 158, in get_readwrite_instance
    rc = db.db_setup()

  File "/usr/local/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 246, in db_setup
    self.lastblock = self.get_lastblock(self.impl, self.working_dir)

  File "/usr/local/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 518, in get_lastblock
    rows = cls.db_query_execute(con, query, (), verbose=False)

  File "/usr/local/lib/python2.7/site-packages/virtualchain/lib/indexer.py", line 390, in db_query_execute
    log.error("\n".join(traceback.format_stack()))

Abort trap: 6

```

**Comment by jcnelson** [comment]
Hey @nsipplswezey, sorry to see you're still having trouble.

Can you try moving your `~/.blockstack-server` out of the way, and then try running `blockstack-core --debug fast_sync` with a fresh, empty `~/.blockstack-server`?

**Comment by nsipplswezey** [comment]
That makes sense to try. I’ll give it a shot this weekend and followup. My expectation, without looking too deeply into it, is a new .db should be created after the check for an existing .db file resolves false and that new .db will either work as intended or yield more info. Thanks for the prompt response!

**Comment by nsipplswezey** [comment]
@jcnelson Thanks that did it. This seems like something that emerged from doing initial setup with an earlier version of blockstack-core and then upgrading.

Assuming a new user accepts the configuration defaults, are there any obvious issues with moving `~/.blockstack-server` out of the way as a first-line check when running into future `fast_sync` issues? Is there a known case where you absolutely would not want to generate a new `~/.blockstack-server` as a debugging step?

Depending on that, I'll walk back through this issue and look to see what small additions –if any– might be made to error messages I ran into that might thoughtfully nudge folks towards getting unblocked. And I'll take a look at the error message issues @jackzampolin mentioned above. Thanks for the help!

**Comment by jcnelson** [comment]
Glad to hear you got it working!

> Assuming a new user accepts the configuration defaults, are there any obvious issues with moving ~/.blockstack-server out of the way as a first-line check when running into future fast_sync issues? Is there a known case where you absolutely would not want to generate a new ~/.blockstack-server as a debugging step?

No, that should be safe.  However, we need to be able to preserve the `~/.blockstack-server/blockstack-server.ini` file across `fast_sync` invocations, since we have devops scripts that assume this (and it makes testing easier).  The `blockstack-core` node is smart enough to migrate its config file.

**Comment by nsipplswezey** [comment]
Awesome.
